### ISSUE TITLE
Feature / Chat improvements

### ISSUE THREAD

**Issue by Bratanov** [Bratanov/community-driven-radio#49]
- [x] message timestamp #52
- [x] emoji list :zucc: #52
- [x] двуеточие след името! #52
- [ ] работещи линкове
- [ ] reactions? some notes in https://github.com/Bratanov/community-driven-radio/pull/52 descr.
- [x] Чата сам си scroll-ва най-долу при нови съобщения дори когато съм scroll-нал нагоре, за да чета старите съобщения от чата :scroll: #52
- [ ] Chat pagination (load messages with a limit from history and *Show more* button to load older records); Prerequisites: Chat timestamps; Can be taken out into a separate issue
- [x] Different color for system messages (Now playing) #52

**Comment by IvayloAtanasov** [comment]
We may want to add messages pagination as well. Currently the chat is filled up with messages from the beginning of time.

**Comment by HristoEftimov** [comment]
When you try to add a song which is already in the queue, a message `This song is already in the queue. Try voting for it instead.` appears. It will be cool if, on message press to scroll your Queue list to the song otherwise, you have to scroll through the list and to find it.
